window.HELP_FAQS = [
  { q: "What is Bizgarh?", a: "Bizgarh is an education classroom for Indian traders and long-term investors. You get recorded courses, live webinars, mentorship desks, and optional 1:1 calls. We teach process, risk, and journals — not tips." },
  { q: "Is Bizgarh investment advice?", a: "No. Everything here is education. You write your own process and size. We do not give buy or sell calls or manage portfolios." },
  { q: "Do you manage money or run a PMS?", a: "No. Bizgarh is a classroom. We do not manage money, run a PMS, or place trades for you." },
  { q: "Do you send trading tips?", a: "No. Mentors show a process. Community rooms are for notes and follow-ups, not tips." },
  { q: "Who is Bizgarh for?", a: "Beginners who want a first plan, working professionals who need a written desk, and traders who want a journal instead of a tip feed." },
  { q: "What is the difference between a course, a webinar, and a mentorship?", a: "A course is a recorded classroom you finish at your pace. A webinar is one live session. A mentorship is a multi-week live desk with the same mentor." },
  { q: "Do I need an account?", a: "Yes. Login to enroll, join a live room, continue a classroom, or open certificates. After login you land on your dashboard." },
  { q: "How do I create an account?", a: "Open Join Bizgarh from Login, enter your name, email, and password. You can also continue with Google if that button is shown." },
  { q: "How do I log in?", a: "Use the Login button, enter the email on your account and your password. After a successful login you open the dashboard." },
  { q: "I forgot my password. What do I do?", a: "Use Forgot password on the login screen. We send a 6-digit OTP to that Gmail. Enter it, then set a new password." },
  { q: "The OTP is not arriving.", a: "Check spam and that you typed the same Gmail as your account. Wait a minute, then tap Resend. Do not share the code with anyone." },
  { q: "Can I change my name or email?", a: "Update your name in My Profile. Email is the login key — write to desk@bizgarh.com if you need it moved." },
  { q: "Where is My Profile?", a: "Open the avatar menu and choose My Profile, or go to Account from the same menu." },
  { q: "Why do I land on the dashboard after login?", a: "Logged-in learners continue from Welcome back instead of the public homepage." },
  { q: "How do I log out?", a: "Open the avatar menu and tap Logout. That ends the session on this browser." },
  { q: "Can I use Bizgarh on more than one device?", a: "Yes. Log in with the same email. Progress for classrooms follows that account." },
  { q: "Is there a mobile app?", a: "You use the website in your mobile browser. Pages, the player, and live rooms are built for phones." },
  { q: "Which browsers work best?", a: "Current Chrome, Edge, or Safari. Keep the browser updated so the live room and player can run." },
  { q: "How do I start if I am new?", a: "Open Courses, pick a Beginner or Hindi classroom, or sit in a live webinar first. Mentorships are better once you already keep a journal." },
  { q: "Where is the course library?", a: "Open Courses. Filter with chips such as Beginners, Hindi, Options, Investing, and Charts." },
  { q: "How do I enroll in a course?", a: "Open a course card and complete enroll while logged in. The classroom then appears on your dashboard and in My Learning." },
  { q: "Can I watch a course at my own pace?", a: "Yes. Courses are recorded. Your last lesson and completion percent are saved to your account." },
  { q: "Will my course progress be saved?", a: "Yes. Continue learning on the dashboard resumes the same lesson. My Learning shows the percent." },
  { q: "How do I continue a classroom?", a: "Tap Continue learning on the dashboard, or open My Learning → My Courses and choose the card." },
  { q: "What is in Bonus resources on a course?", a: "Student access to the practice desk and the course community after you own that classroom." },
  { q: "Why is Community locked on a course?", a: "The Telegram room opens only after you enroll in that course. It is for students, not a public tip feed." },
  { q: "Which language is original on a course?", a: "The first language chip is the original track. Most desks run in English and Hindi as listed on the page." },
  { q: "Can I watch a course on my phone?", a: "Yes. The player stays on the screen. Use play, next, mute, and fullscreen from the bar." },
  { q: "The video player will not start.", a: "Check your connection, refresh the lesson, and try Chrome. Write to desk@bizgarh.com with the course title and lesson name if it still fails." },
  { q: "Can I skip ahead in a course?", a: "Yes. Open the lesson list and pick the topic you want. Completion still needs every lesson for a certificate." },
  { q: "How long do I keep course access?", a: "As long as the course stays on your Bizgarh account. Certificates stay available after you finish." },
  { q: "Are courses investment advice?", a: "No. Classrooms teach process and risk. They are not recommendations." },
  { q: "When is a course certificate issued?", a: "After you complete every lesson in that classroom. It then appears in My Certificates." },
  { q: "Where do I view my certificates?", a: "My Learning → My Certificates, or Quick Actions → My Certificates on the dashboard." },
  { q: "How do I download a certificate?", a: "Open the certificate and tap Download PNG. Your account name and the course title are printed on it." },
  { q: "Can I print a certificate as PDF?", a: "Yes. Use Print / PDF and save from the browser print dialog." },
  { q: "The certificate page says it is not issued yet.", a: "Finish the remaining lessons, then return. Certificates are for completed classrooms, not for a webinar or mentorship alone." },
  { q: "Whose name is on the certificate?", a: "The name on your Bizgarh account. Update it in My Profile before you download if you need a correction." },
  { q: "Do webinars give a certificate?", a: "Registered learners get a certificate of participation after the webinar session." },
  { q: "Do mentorships give a course certificate?", a: "Mentorships are live desks. Course-completion certificates come from finishing a recorded classroom." },
  { q: "What is a live webinar?", a: "A single live session with a mentor inside the Bizgarh room. Enroll on the webinar page, then tap Join Now at start time." },
  { q: "Are webinars free?", a: "Most webinars are listed as free for registered learners. The detail page shows the price if a session is paid." },
  { q: "How do I enroll in a webinar?", a: "Open the webinar card, tap Enroll Now, and log in. The page then shows Join Now and Join community." },
  { q: "Where do I join a webinar when it goes live?", a: "From the webinar page or from Your upcoming live sessions on the dashboard. Join Now opens the Bizgarh room." },
  { q: "Will I get a webinar recording?", a: "If the mentor uploads one, registered learners see it on the same webinar page." },
  { q: "What if I miss the webinar live time?", a: "Register anyway. If a recording is uploaded, you can watch it on that page." },
  { q: "Do I need a paid course before a webinar?", a: "No. A webinar stands on its own. A related classroom is useful but not required." },
  { q: "What should I bring to a webinar?", a: "A journal and one question you already have. You write the process as the mentor works — it is not a tip feed." },
  { q: "Can I join a webinar from my phone?", a: "Yes. Use your mobile browser. Allow camera or mic only if the room asks and you want to speak." },
  { q: "What is Join community on a webinar?", a: "A Telegram room for reminders and follow-ups for that session. It is not a broadcast of calls." },
  { q: "How is a live class different from a webinar?", a: "Both run in the Bizgarh room. Webinars are public sessions. Live classes may be tied to a classroom or mentorship desk." },
  { q: "Where does live video run?", a: "Inside Bizgarh, not on Zoom. Use Join Now or Join desk from the detail page." },
  { q: "Do I need to register before joining a live room?", a: "Yes. Enroll on the detail page while logged in. Join then opens the room." },
  { q: "The live room says connecting.", a: "Wait a few seconds, check camera or mic permission if asked, then refresh. Write to desk@bizgarh.com with the session title if it stays stuck." },
  { q: "Can I join live without a camera?", a: "Yes. You can watch. Turn the camera on only if you want to speak and the room allows it." },
  { q: "What is a mentorship program?", a: "A guided multi-week desk with a working trader. You enroll, join live sessions inside Bizgarh, use the community room, and review recordings when they are uploaded." },
  { q: "How is mentorship different from a webinar?", a: "A webinar is one session. A mentorship runs several weeks with a curriculum, weekly review, and a seat in the desk community." },
  { q: "How do I enroll in a mentorship?", a: "Open a program, tap Enroll Now, and log in. The same page then shows Already enrolled, Join desk, and Join community." },
  { q: "What happens after I enroll in a mentorship?", a: "The program is saved under My Mentorship on the dashboard and in My Learning. You join the desk and the Telegram room from the program page." },
  { q: "How do I join the mentorship desk?", a: "Tap Join desk when you are enrolled. You can also open the program from My Learning → My Mentorship." },
  { q: "Can I skip a mentorship session?", a: "Prefer not to. If you miss one, the recording — when uploaded — stays on the program page for enrolled learners." },
  { q: "How long do mentorship recordings stay?", a: "One year from the day you enroll, on that program page, whenever a recording is uploaded." },
  { q: "Will I get to ask doubts in mentorship?", a: "Yes. Live Q&A is part of each session. The community room is for short follow-ups, not personal trading calls." },
  { q: "What is the mentorship community room?", a: "An exclusive Telegram room for that desk: session notes, reminders, and follow-up questions. It is not a tip channel." },
  { q: "What does Request a callback do?", a: "It sends your name and email to the desk. Someone from Bizgarh will contact you about that program. It does not enroll you." },
  { q: "Who is a mentorship for?", a: "Learners who want a written process they can run after the live desk closes. It is not a signals service." },
  { q: "What should I prepare before the first mentorship session?", a: "Bring the broker you already use, a journal, and the basics listed under Key concepts on the program page." },
  { q: "Can I attend mentorship on mobile?", a: "Yes. Enroll, join the desk, and watch recordings in your mobile browser." },
  { q: "What language is the mentorship desk in?", a: "Mentors teach in English and Hindi as needed. Curriculum text on the page is in English." },
  { q: "What if mentorship seats are full?", a: "The page shows seats left. If a batch is full, request a callback and we will tell you about the next desk." },
  { q: "Where do I see my mentorships?", a: "Dashboard → My Mentorship, or My Learning → My Mentorship." },
  { q: "How long is a 1:1 call?", a: "45 minutes on your journal, risk, or a stuck setup. It is not a live trading call service." },
  { q: "How do I book a 1:1?", a: "Open Live → Book a 1:1 call, pick a topic and time, and submit while logged in." },
  { q: "When do I get the 1:1 room?", a: "After the desk approves your slot. You join inside Bizgarh with the same account email." },
  { q: "What should I write in 1:1 notes?", a: "What is stuck: a setup, a size rule, or a journal week. Bring that to the call." },
  { q: "Can I pick a mentor for a 1:1?", a: "Yes, or leave Any available. We assign someone who teaches that topic." },
  { q: "Is a 1:1 investment advice?", a: "No. The mentor reviews your process. You still make your own decisions." },
  { q: "What is Continue learning on the dashboard?", a: "The classroom you last opened that is not finished. Tap it to resume the same lesson." },
  { q: "Where are my upcoming live sessions?", a: "On the dashboard under Your upcoming live sessions. Mentorships sit under My Mentorship." },
  { q: "What is in My Learning?", a: "Four tabs: My Courses, Webinars, My Mentorship, and My Certificates." },
  { q: "What is in My Courses?", a: "Classrooms you own. Ongoing is not finished. Completed is 100% watched." },
  { q: "What is in the Webinars tab?", a: "Sessions you enrolled in. Ongoing is still scheduled or live. Completed has ended." },
  { q: "What is in My Mentorship on My Learning?", a: "Programs you enrolled in. Open a card to join the desk, read the curriculum, or enter the community." },
  { q: "I enrolled but the tab count did not go up.", a: "Refresh after login. Lists are stored on this browser for your account email." },
  { q: "Can I filter Ongoing and Completed?", a: "Yes. The chips under a tab filter that list only." },
  { q: "How do I search the site?", a: "Use the header search for courses and mentors. On this Help page, use the FAQ search bar." },
  { q: "How do I open Help?", a: "Quick Actions → Help, or Contact in the footer. This page is Help." },
  { q: "How fast does the desk reply?", a: "We reply to desk@bizgarh.com and the form on this page within one working day." },
  { q: "What should I include in a help message?", a: "Your login email, the course or program title, and what is broken: enroll, player, live room, or certificate. Do not send passwords or OTPs." },
  { q: "Can I ask a trading doubt on this form?", a: "Use the community room or a 1:1 for process questions. This form is for access and account help." },
  { q: "What is the desk email?", a: "desk@bizgarh.com. Use the same email as your Bizgarh account when you write." },
  { q: "Do classrooms run in Hindi?", a: "Yes. Filter Hindi on Courses. Mentors also teach in Hindi on many live desks." },
  { q: "Do I need a new broker?", a: "No. Use the broker you already have. Classrooms do not ask you to switch." },
  { q: "Do I need TradingView or a special chart tool?", a: "Only if a lesson says so. Most desks work with the chart you already use." },
  { q: "Should I trade live during class?", a: "Only if you already have a written size and invalidation. The classroom is for process, not for copying a click." },
  { q: "What is a journal on Bizgarh?", a: "A written note of setup, size, invalidation, and what you will skip. Mentors ask you to keep one." },
  { q: "What does education only mean?", a: "Ideas, charts, and examples are for learning. They are not instructions to buy or sell." },
  { q: "Can I share my login?", a: "No. Keep the account on your email only. Sharing can lock you out of live rooms." },
  { q: "Is my progress private?", a: "Your classroom progress and enrollments stay on your account. Mentors see live-room attendance, not your broker." },
  { q: "How do I share a course link?", a: "Open the course and use Share if shown, or copy the page URL from the browser." },
  { q: "Where are mentorship programs listed?", a: "Open Mentorship from Explore or /mentorship. Upcoming and ongoing desks are on that page." },
  { q: "Where are webinars listed?", a: "Open Live or /live#webinars. Each card opens a detail page with enroll and Join Now." },
  { q: "Can I download a mentorship curriculum?", a: "Yes. On the program page tap Download curriculum. It saves a text file of the live outline." },
  { q: "What is Already enrolled?", a: "You are in that webinar or mentorship. Use Join Now or Join desk instead of Enroll." },
  { q: "What is SAVE % on a card?", a: "The difference between the listed full price and the current price on that card." },
  { q: "Do I need to pay again to rewatch a course?", a: "No. Once the classroom is on your account, open it from My Learning as often as you like." },
  { q: "Can I join a live room from My Learning?", a: "Open the webinar or mentorship card from the matching tab, then Join Now or Join desk on the detail page." },
  { q: "The page looks old after an update.", a: "Hard refresh with Ctrl+F5 or clear the tab cache, then open the page again." },
  { q: "Who teaches on Bizgarh?", a: "Working traders listed on each course, webinar, and mentorship page. Open Know your instructor on the program page." },
  { q: "How do I raise a ticket from Account?", a: "Account → tickets, or send a note on this Help page. Both reach the desk." },
  { q: "What if I cannot find an FAQ here?", a: "Try another keyword in the search bar above, or send a message on this page with your login email." }
];
